// SPDX-License-Identifier: GPL-3.0-only

pub mod a11y;
pub mod animated_resize;
pub mod blur;
pub mod corner_radius;
pub mod drm;
pub mod exclusive_mode;
pub mod home_visibility;
pub mod image_capture_source;
pub mod layer_corner_radius;
pub mod layer_shadow;
pub mod output_configuration;
pub mod output_power;
pub mod overlap_notify;
pub mod screencopy;
pub mod surface_embed;
pub mod toplevel_info;
pub mod toplevel_management;
pub mod voice_mode;
pub mod workspace;
